name: flowder_v2
description: Persistent file downloader manager, start, pause, resume, cancel your download.
version: 1.0.1
homepage: https://github.com/khangpt/flowder_v2

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dio: 5.1.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter